### ISSUE TITLE
Year Planning Guidance

### ISSUE THREAD

**Issue by barrosgg** [mozillabrasil/mozilla-campus-clubs#1]
Nós precisamos de ajuda para localizar este guia, apenas este!
https://github.com/mozillabrasil/mozilla-campus-clubs/blob/gh-pages/_pages/yearplanning.md

**Comment by maykonchagas** [comment]
@barrosgeraldo eu posso colaborar. qual é o prazo?

**Comment by barrosgg** [comment]
hummm, então isso é algo urgente porque eu gostaria de passar para os capitães na terça-feira.

**Comment by maykonchagas** [comment]
@barrosgeraldo ok, considere localizado.

**Comment by barrosgg** [comment]
Acho que ainda não surgiu efeito. :(

**Comment by maykonchagas** [comment]
Ahm? não, calma @barrosgeraldo eu disse pra considerar localizado, não que já estava localizado. Inicio hoje a noite, no máximo amanhã a noite estará completo. Vou atualizando via commit. MozLove!

**Comment by maykonchagas** [comment]
@barrosgeraldo done!

**Comment by barrosgg** [comment]
Obrigado Maykon, manda seu mozillians e endereço por email, pls.
